# NLTK là một thư viện Python phổ biến được sử dụng cho NLP.
####    -NLP(Natural Language Processing) là khái niệm để chỉ các kĩ thuật, phương pháp thao tác trên ngôn ngữ tự nhiên bằng máy tính.
Các ứng dụng cơ bản của NLP :
            1. Chế tạo các hệ thống Máy dịch, ví dụ như Google translation.
            2. Xử lý văn bản và ngôn ngữ.
            3. Chiết suất thông tin.
            4. Tóm tắt văn bản.
            5. Phân loại văn bản.

## So sánh NLTK và 1 số thư viện khác
    -Nltk là thư viện chuyên dùng để xử lý và phân tích các văn bản phi cấu trúc, NLTK được sử dụng chủ yếu cho các tác vụ NLP chung (mã hóa, gắn thẻ POS, phân tích cú pháp, v.v.) phục vụ NGHIÊN CỨU HỌC THUẬT do vậy NLTK hỗ trợ nhiều ngôn ngữ khác nhau tuy nhiên đối với dataset lớn thì tốc độ chưa được tối ưu tốt bằng các công cụ khác như Sklearn, Space... và NLTK không có bất kỳ hỗ trợ nào cho việc vectơ từ.
    Trong khi đó các công cụ khác như Sklearn, sPacy thì chuyên về HỌC MÁY (classification, clustering, etc.), nó là 1 thư viện có tính hệ thống, cung cấp nhiều mô hình, tính năng mà Nltk chưa có như tf-idf, ngram, classification/clustering method... do được xây dựng chuyên về học máy nên tốc độ có tốt hơn NLTK và dễ sử dụng hơn
    
    vd: 1 thống kê của thư viện sPacy đã test và đưa ra so sánh về 2 thư viện
![image.png](spicy.png)

![image.png](compare.png)

# Import thư viên

In [1]:
import nltk
from nltk import *

# Basic NLP Tasks with NLTK

#### 1. Counting vocabulary of words

In [2]:
text = """Hãng tin AFP dẫn lời tổ chức Đài quan sát Nhân quyền Syria (SOHR) đưa tin,
ít nhất 17 người đã thiệt mạng trong vụ không kích ngày 25/2 của Mỹ nhằm vào các nhóm dân quân nghi
thân Iran trên lãnh thổ Syria. Đây đều là thành viên của các nhóm nói này.
Các cuộc tấn công đã phá hủy 3 xe tải chở đạn... Có nhiều thương vong. 
Thông tin sơ bộ là ít nhất 17 người đã thiệt mạng, giám đốc SOHR Rami Abdul Rahman, cho hay."""

In [3]:
# Import thư viện
from nltk import FreqDist

In [4]:
# split đoạn văn bản ra bởi thành 1 list
list_text = text.split(' ')
count_words = FreqDist(text.split(' '))
count_words

FreqDist({'đã': 3, 'tin': 2, 'nhất': 2, '17': 2, 'người': 2, 'thiệt': 2, 'của': 2, 'các': 2, 'nhóm': 2, 'là': 2, ...})

In [5]:
# Cách để lấy list từ
count_words.keys()

# cách để lấy số lần xuất hiện 
count_words['tin']

# cách lấy ra các từ xuất hiện nhiều nhât, ví dụ top 3
count_words.most_common(3)

# cách lựa chọn từ theo nhu cầu, ví dụ độ dài từ >=3, tần suất >1
freqwords = [w for w in count_words if len(w) >=3  and count_words[w] > 1]
freqwords

['tin', 'nhất', 'người', 'thiệt', 'của', 'các', 'nhóm']

#### 2. Stemming
Stemming là kỹ thuật dùng để biến đổi 1 từ về dạng gốc (được gọi là stem hoặc root form) bằng cách cực kỳ đơn giản là loại bỏ 1 số ký tự nằm ở cuối từ mà nó nghĩ rằng là biến thể của từ. 

Bởi vì nguyên tắc hoạt động của stemmer rất là đơn giản như vậy cho nên tốc độ xử lý của nó rất là nhanh, và kết quả stem đôi khi không được như chúng ta mong muốn

In [6]:
input1 = "List listed lists listing listings"
words1 = input1.lower().split(' ')
words1
words2 = 'go went goes'.split(' ')

In [7]:
porter = nltk.PorterStemmer()
[porter.stem(t) for t in words1]

['list', 'list', 'list', 'list', 'list']

In [8]:
[porter.stem(t) for t in words2]

['go', 'went', 'goe']

#### 3. Lemmatization
Khác với Stemming là xử lý bằng cách loại bỏ các ký tự cuối từ một cách rất heuristic, Lemmatization sẽ xử lý thông minh hơn bằng một bộ từ điển tuy nhiên tốc độ xử lí k nhanh bằng stemming. Trong các ứng dụng xử lý NLP mà cần độ chính xác cao hơn và thời gian không quan trọng, người ta có thể sử dụng Lemmatization

In [9]:
WNlemma = nltk.WordNetLemmatizer()
[WNlemma.lemmatize(t) for t in words2[:20]]

['go', 'went', 'go']

#### 4. Tokenization

In [11]:
# Tách văn bản theo while space và stopword
nltk.word_tokenize('hôm nay trời đẹp ghê! chắc nên ra ngoài. một chút')

['hôm',
 'nay',
 'trời',
 'đẹp',
 'ghê',
 '!',
 'chắc',
 'nên',
 'ra',
 'ngoài',
 '.',
 'một',
 'chút']

In [22]:
# nhận 1 string đã bị tokenize thành từ đơn sau đó maz hóa lại, merge các từ đơn lẻ thành 1 từ bằng cách sử dụng MWE
from nltk.tokenize import MWETokenizer
tokenizer = MWETokenizer([('a', 'little'), ('a', 'little', 'bit'), ('a', 'lot')])
tokenizer.tokenize('a little bit longer than you think, wait me a little, it take time a lot'.split())

['a_little_bit',
 'longer',
 'than',
 'you',
 'think,',
 'wait',
 'me',
 'a',
 'little,',
 'it',
 'take',
 'time',
 'a_lot']

In [26]:
# tách văn bản theo regexp
from nltk.tokenize import RegexpTokenizer
s = "Good muffins cost $3.88 in New York.  Please buy me two of them, Thanks."
# regexp để nhận kí tự $3.88 và các while space(mặc định)
tokenizer = RegexpTokenizer('\w+|\$[\d\.]+|\S+')
tokenizer.tokenize(s)[:5]

['Good', 'muffins', 'cost', '$3.88', 'in']

In [25]:
nltk.word_tokenize(s)[:5]

['Good', 'muffins', 'cost', '$', '3.88']

In [29]:
# tách văn bản only by whilespace (mặc định là whilespace và punc)
from nltk.tokenize import WhitespaceTokenizer
WhitespaceTokenizer().tokenize('hôm nay. là! thứ 2@ đó')

['hôm', 'nay.', 'là!', 'thứ', '2@', 'đó']

In [30]:
#tách văn bản theo dòng
from nltk.tokenize import LineTokenizer
s = "Good muffins cost $3.88\nin New York.  Please buy me\ntwo of them.\n\nThanks."
LineTokenizer(blanklines='keep').tokenize(s)

['Good muffins cost $3.88',
 'in New York.  Please buy me',
 'two of them.',
 '',
 'Thanks.']

In [47]:
# tách từ và chỉnh sửa lại cho đúng từ điển lựa chọn
from nltk.tokenize.stanford import StanfordTokenizer
s = "The colour of the wall is blue."
# StanfordTokenizer(options={"americanize": True}).tokenize(s)

### ->> ['The', 'color', 'of', 'the', 'wall', 'is', 'blue', '.']

# từ điển stanford có thể dùng cho nhiều ngôn ngữ khác

In [49]:
# detokenzi 
from nltk.tokenize.treebank import TreebankWordDetokenizer
toks = ['hello', ',', 'i', 'ca', "n't", 'feel', 'my', 'feet', '!', 'Help', '!', '!']
twd = TreebankWordDetokenizer()
twd.detokenize(toks)

"hello, i can't feel my feet! Help!!"

In [21]:
# Tách văn bản theo đoạn văn
nltk.sent_tokenize(text)

['Hãng tin AFP dẫn lời tổ chức Đài quan sát Nhân quyền Syria (SOHR) đưa tin,\nít nhất 17 người đã thiệt mạng trong vụ không kích ngày 25/2 của Mỹ nhằm vào các nhóm dân quân nghi\nthân Iran trên lãnh thổ Syria.',
 'Đây đều là thành viên của các nhóm nói này.',
 'Các cuộc tấn công đã phá hủy 3 xe tải chở đạn... Có nhiều thương vong.',
 'Thông tin sơ bộ là ít nhất 17 người đã thiệt mạng, giám đốc SOHR Rami Abdul Rahman, cho hay.']

#### 5. Stopwords
- ký tự, từ mà không có ý nghĩa trong câu, nếu không xóa đi thì sẽ ảnh hưởng đến kết quả xử lí (ví dụ: tăng feature lên không cần thiết, khi biến đổi text -> vector làm thay đổi chúng so với các từ cùng loại mà không có stopword...)

In [37]:
# nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

ex_stopword = "The government has laid out plans for gradual reopening."
stop_word = stopwords.words("english")
len(stop_word)

179

In [39]:
word_tkn = word_tokenize(ex_stopword)
[x for x in word_tkn if x not in stop_word]

['The', 'government', 'laid', 'plans', 'gradual', 'reopening', '.']

#### 6. Part of speech tagging
- Xác định danh từ, tính từ, trạng từ ... trong text

![image.png](pos.png)

In [57]:
text = "Children shouldn't drink a sugary drink before bed."
tkn_text = word_tokenize(text)
nltk.pos_tag(tkn_text)

[('Children', 'NNP'),
 ('should', 'MD'),
 ("n't", 'RB'),
 ('drink', 'VB'),
 ('a', 'DT'),
 ('sugary', 'JJ'),
 ('drink', 'NN'),
 ('before', 'IN'),
 ('bed', 'NN'),
 ('.', '.')]

# II: Các bước phân loại text

#### 1. Xử lý features
- Loại bỏ stopword (nltk) và punctuation (string library)
- Nomalization text bằng cách lowercase hoặc uppercase -> hạn chế sinh ra các feature đồng nghĩa nhưng xuất hiện nhiều lần do cách viết hoa
- Stemming hoặc lemmatization đối với tiếng anh. Tiếng việt thì k cần thiết do các từ k có biến thể. Có thể sử dụng underthesea để nối các từ lại vì tiếng việt các từ phải ghép vào mới có nghĩa, ví dụ: Ngôi nhà (2).  Tiếng anh thì chỉ cần House
- Nhóm các từ đồng nghĩa ví dụ: (Buy - Purchase) hoặc tiếng việt (bát cơm - tô cơm...)
- Convert text sang vector (CountVecterizer, tf-idf, ngram)

#### 2. Lựa chọn mô hình
Các mô hình phân loại phổ biến: Naive Bayes, Supper Vector Machine, Decision tree, LogisticRegression...

### 2.1, Bayes 
Nguyên tắc: Tính xác suất có điều kiện của input. So sánh kết quả -> phân loại input đó vào nhóm có xác suất cao nhất.

Công thức cơ bản: probability( y|X) = ( Pr(y) x Pr(X|y) ) / Pr(x)

Tuy nhiên Bayes chỉ quan tâm tới cái nào có xác suất cao nhất do đó mô hình này chỉ quan tâm đến argmax Pr(Y) x Pr(X|y). Ví dụ:
![image.png](bayes.png)

##### Input đầu vào Dear Friends, xác định đây là spam hay không spam, theo công thức ta có:
        (1) Pr(Not Spam|Dear Friend) = Pr(Not Spam) * Pr(Dear|Not spam) * Pr(Friend|Not spam) = 0.67 * 0.47 * 0.29 = 0.09
        (2) Pr(Spam|Dear Friend) = Pr(Spam) * Pr(Dear|Spam) * Pr(Friend|Spam) = 0.33 * 0.29 * 0.14 = 0.01
         => Do xác suất của Not Spam cao hơn => Phân loại nó là Not Spam
         
#### Bam!!! : Nếu từ cần tìm không có trong tệp dữ liệu, ví dụ: Money thì sẽ xử lý sao ???
        Khi đó Pr(Not Spam|dear sir) = Pr(Spam|dear sir) = 0 ??
        
### ====> Adding dummy count
Thêm biến giả sir vào trong tệp dữ liệu, +1 vào các từ đã có sẵn rồi tính toán lại

In [12]:
from nltk import NaiveBayesClassifier
import pandas as pd

In [13]:
df = pd.DataFrame()
df['X'] = ['Thời tiết hôm nay rất đẹp', 'Tối nay Arsenal đá với ManUnt', 
           'Thời tiết hôm nay thật đẹp cho trận đấu này','Trận đấu hôm nay có thể phải diễn ra với thời tiết xấu']
df['Y'] = ['Thời tiết', 'Bóng đá','Bóng đá','Bóng đá']
df

X          Y
0                          Thời tiết hôm nay rất đẹp  Thời tiết
1                      Tối nay Arsenal đá với ManUnt    Bóng đá
2        Thời tiết hôm nay thật đẹp cho trận đấu này    Bóng đá
3  Trận đấu hôm nay có thể phải diễn ra với thời ...    Bóng đá

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()
vect.fit(df.X)
X_train = vect.transform(df.X).todense()
X_train

matrix([[0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
         1],
        [1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
         0],
        [0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
         1],
        [0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
         0]], dtype=int64)

In [15]:
Y_train = [1 if i =='Thời tiết' else 0 for i in df.Y]
Y_train

[1, 0, 0, 0]

In [16]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB().fit(X_train,Y_train)
model

GaussianNB()

In [17]:
text_predict = 'tối nay thời tiết sẽ mưa'
vect.transform([text_predict]).todense()

matrix([[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
         0]], dtype=int64)

In [18]:
model.predict(vect.transform([text_predict]).todense())

array([0])

#### 3. Kiếm tra model
- Chia dữ liệu ra làm 2 phần test và phần train.
    + from sklearn import model_selection
    + x_train, y_train, x_test, y_test = model_selection.train_test_split(training_data,training_label,test_size= 0.75, random_state = 0)
- Build model trên list data train
    + from sklearn import naive_bayes
    + model = naive_bayes.MultinomialNB().fit(train_data, train_label)
- Predict dựa trên dữ liệu test rồi so sánh kết quả
    + label_predict = model.predict(test_data)
    + metrics.f1_score(test_label, label_predict)